name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Unit tests
        run: |
          python -m unittest tests/unit/test_myutils.py

      - name: Functional tests (ssshtest)
        run: |
          chmod +x tests/functional/test_printfires.sh
          bash tests/functional/test_printfires.sh

      - name: Style checks
        run: |
          flake8 .
